"""Version and build-revision detection utilities for the spec-kitty CLI."""

import importlib
import subprocess
from pathlib import Path

from kernel._safe_re import re


_REVISION_PATTERN = re.compile(r"^[0-9a-fA-F]{7,40}$")


def _normalize_revision(value: object) -> str | None:
    if not isinstance(value, str) or not _REVISION_PATTERN.fullmatch(value):
        return None
    return value[:12].lower()


def _read_git_revision(repo_root: Path) -> str | None:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=repo_root,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            check=False,
            timeout=2,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if result.returncode != 0:
        return None
    return _normalize_revision(result.stdout.strip())


def get_build_revision() -> str:
    """Return the exact source revision for diagnostic version output.

    Source and editable checkouts use their live Git HEAD. Installed artifacts
    use the revision generated by the build hook. ``unknown`` is reserved for
    environments where neither source is available.
    """
    repo_root = Path(__file__).resolve().parents[2]
    if (repo_root / ".git").exists():
        live_revision = _read_git_revision(repo_root)
        if live_revision:
            return live_revision

    try:
        build_info = importlib.import_module("specify_cli._build_info")
    except ModuleNotFoundError:
        return "unknown"
    return _normalize_revision(getattr(build_info, "BUILD_REVISION", None)) or "unknown"


def read_version_from_pyproject() -> str | None:
    """Read version from pyproject.toml as fallback.

    Returns:
        Version string if found, None otherwise
    """
    try:
        # Find pyproject.toml relative to this file
        package_root = Path(__file__).parent.parent.parent
        pyproject_path = package_root / "pyproject.toml"

        if not pyproject_path.exists():
            return None

        content = pyproject_path.read_text()

        # Match: version = "X.Y.Z"
        pattern = re.compile(r'^\s*version\s*=\s*"(\d+\.\d+\.\d+[^"]*)"', re.MULTILINE)
        match = pattern.search(content)

        if match:
            result: str = match.group(1)
            return result

        return None
    except Exception:
        # Any error reading file -> return None
        return None


def get_version() -> str:
    """Get spec-kitty version with smart fallback strategy.

    Priority:
    1. importlib.metadata for the resolved CLI package name
    2. pyproject.toml (fallback for editable installs)
    3. "0.0.0-dev" (last resort if both fail)

    Returns:
        Version string
    """
    try:
        from importlib.metadata import version as get_metadata_version

        from specify_cli.distribution.package_name import resolve_cli_package_name

        return get_metadata_version(resolve_cli_package_name())
    except Exception:  # noqa: S110
        pass

    # Try reading from pyproject.toml (editable installs)
    pyproject_version = read_version_from_pyproject()
    if pyproject_version:
        return pyproject_version

    # Last resort fallback
    return "0.0.0-dev"
