#!/usr/bin/env python3
"""Occurrence-map-driven bulk reference rewriter (Mission B, IC-05b).

Mission B (*Common Docs Structural Move*, ``01KW3SBK``) folds the top-level
``architecture/`` tree into ``docs/`` and re-sections the Divio doc dirs.  This
tool rewrites every in-tree *reference* to a moved doc path, driven by the
mission ``occurrence_map.yaml`` ``moves:`` block — the authoritative old→new
path-pair spine (#1815 structural-restructure workaround).

Design contract
---------------

* **Occurrence-map-driven.**  The ``moves:`` pairs are the substitution table;
  the ``exceptions:`` / per-category ``action:`` fields are the *filter*.  No
  hard-coded "architecture/ → docs/" heuristic — only declared moves are applied.
* **``do_not_change`` is enforced.**  Files under ``kitty-specs/`` (immutable
  mission snapshots), ``docs/1x|2x/`` (delete+redirect shadow trees),
  ``docs/adr/`` (immutable ADR decision bodies — C-002 content-invariance), the
  historical ``CHANGELOG.md`` / ``docs/changelog/`` release record, the serialized
  inventory lockfile, and the golden charter-synthesis fixtures are skipped.  The
  ``serialized_keys`` surfaces (``toc.yml`` href values, ``docfx.json`` globs,
  ``llms.txt`` entries — WP09) and YAML *frontmatter fields* (WP12) are likewise
  left untouched (frontmatter is split off and never rewritten).  The
  ``code_symbols`` / ``import_paths`` / ``cli_commands`` / ``logs_telemetry``
  ``do_not_change`` categories are respected structurally: those literals use
  dotted module names / command tokens, not slash-delimited doc paths, so the
  path-prefix matcher never touches them.
* **Landing-aware destinations.**  The map's ``to:`` is the destination *root*;
  the actual landing frequently preserves the moved subtree as a subdir
  (``architecture/audits`` → ``docs/architecture/audits``), renames it
  (``docs/engineering_notes`` → ``docs/plans/engineering-notes``), or
  disambiguates files (per-era ``README.md`` → ``README-<era>.md``).  The tool
  resolves the *real* destination against the on-disk tree so rewrites produce
  links that actually resolve, not the coarse ``to:`` directory.
* **Incremental-safe.**  A move whose ``from`` still exists on disk has not
  landed in this lane yet (or is an intentional alias, e.g. root ``CHANGELOG.md``);
  its references are left alone so no link is broken mid-migration.
* **Idempotent + dry-run-able.**  ``--dry-run`` prints the planned blast radius
  without writing; a second real run is a no-op (already-rewritten ``docs/...``
  paths never re-match, guarded by a ``(?<!docs/)`` lookbehind).

This is a committed migration tool, not throwaway: it documents exactly what the
sweep did and lets a reviewer re-run ``--dry-run`` to verify completeness.
"""

from __future__ import annotations

import argparse
import re
from collections.abc import Iterable, Iterator
from dataclasses import dataclass, field
from pathlib import Path

import yaml

# --------------------------------------------------------------------------- #
# Defaults                                                                     #
# --------------------------------------------------------------------------- #

DEFAULT_OCCURRENCE_MAP = (
    "kitty-specs/common-docs-structural-move-01KW3SBK/occurrence_map.yaml"
)
DEFAULT_ROOTS: tuple[str, ...] = ("src", "tests", "docs")
TEXT_SUFFIXES = frozenset({".py", ".md", ".txt", ".rst", ".yaml", ".yml"})

# do_not_change path prefixes (relative, posix). Immutable snapshots / shadow
# trees / historical record — never rewritten.
EXCLUDE_PREFIXES: tuple[str, ...] = (
    "kitty-specs/",
    "docs/1x/",
    "docs/2x/",
    "docs/changelog/",  # historical release record (mirror of root CHANGELOG.md)
    "docs/adr/",  # immutable ADR decision bodies (C-002 content-invariance)
)

# do_not_change directory prefixes that carry golden fixtures (charter
# synthesis snapshots reference example doc paths as data, not live links).
EXCLUDE_DIR_PREFIXES: tuple[str, ...] = ("tests/charter/fixtures/synthesizer/",)

# Serialized-key files (WP09) + the historical/tooling artifacts that own their
# path references outside this category.
EXCLUDE_BASENAMES: frozenset[str] = frozenset(
    {"toc.yml", "docfx.json", "llms.txt", "CHANGELOG.md"}
)

# Exact relative paths never rewritten: the serialized inventory lockfile (a
# tooling artifact regenerated by the inventory pipeline — "stays put"), and the
# tool's own sources / tests that intentionally carry old-path literals.
EXCLUDE_PATHS: frozenset[str] = frozenset(
    {
        "docs/development/3-2-page-inventory.yaml",
        "scripts/docs/bulk_ref_rewrite.py",
        "tests/docs/test_bulk_ref_rewrite.py",
        "tests/docs/test_runtime_read_resolution.py",
    }
)

# Move ``from`` entries that are NOT simple path-rewrites: shadow-tree redirect
# bases (delete+redirect, do_not_change), the in-place serialized DocFX config,
# and the relocate-with-alias CHANGELOG (root copy persists by contract).
SKIP_MOVE_FROMS: frozenset[str] = frozenset(
    {"docs/1x", "docs/2x", "docs/docfx.json", "docs/llms.txt", "CHANGELOG.md"}
)

# Landing disambiguations the coarse ``to:`` cannot express (verified against the
# live tree): the per-era READMEs were suffixed rather than collapsed.
DEST_OVERRIDES: dict[str, str] = {
    "architecture/1.x/README.md": "docs/architecture/README-1.x.md",
    "architecture/2.x/README.md": "docs/architecture/README-2.x.md",
    "architecture/3.x/README.md": "docs/architecture/README-3.x.md",
}


# --------------------------------------------------------------------------- #
# Substitution model                                                          #
# --------------------------------------------------------------------------- #


@dataclass(frozen=True)
class Substitution:
    """A single old-prefix → new-prefix path rewrite."""

    old: str
    new: str
    is_file: bool


def _is_file_path(path: str) -> bool:
    """A move target is a file when its last segment carries an extension."""

    return "." in path.rsplit("/", 1)[-1]


def load_moves(occurrence_map_path: Path) -> list[tuple[str, str]]:
    """Flatten the ``moves:`` block into ``(from, to)`` pairs (trailing-/ trimmed)."""

    data = yaml.safe_load(occurrence_map_path.read_text(encoding="utf-8"))
    pairs: list[tuple[str, str]] = []
    for entry in data.get("moves", []) or []:
        to = str(entry["to"]).rstrip("/")
        froms = entry["from"]
        if isinstance(froms, str):
            froms = [froms]
        for frm in froms:
            pairs.append((str(frm).rstrip("/"), to))
    return pairs


def resolve_destination(old: str, to: str, repo_root: Path) -> str:
    """Resolve the *real* on-disk destination for a moved ``old`` path.

    The map's ``to`` is the destination root; the landing may preserve the
    subtree as a subdir, rename it (``_`` ↔ ``-``), or — for explicit
    disambiguations — land it under an overridden name.  Falls back to the bare
    ``to`` (flattened landing) when no subdir variant exists.
    """

    if old in DEST_OVERRIDES:
        return DEST_OVERRIDES[old]
    base = old.rsplit("/", 1)[-1]
    if _is_file_path(old):
        return f"{to}/{base}"
    candidates = [base]
    if "_" in base:
        candidates.append(base.replace("_", "-"))
    if "-" in base:
        candidates.append(base.replace("-", "_"))
    for candidate in candidates:
        if (repo_root / to / candidate).is_dir():
            return f"{to}/{candidate}"
    return to


def build_substitutions(
    pairs: Iterable[tuple[str, str]],
    repo_root: Path,
    *,
    skip_existing_from: bool = True,
) -> list[Substitution]:
    """Build the active substitution list.

    Skips ``do_not_change`` move ``from`` entries and — when
    *skip_existing_from* — any move whose source still exists on disk (not yet
    landed in this lane, or an intentional alias).  Sorted longest-source-first
    so the most specific prefix wins.
    """

    subs: list[Substitution] = []
    for old, to in pairs:
        if old in SKIP_MOVE_FROMS:
            continue
        if skip_existing_from and (repo_root / old).exists():
            continue
        new = resolve_destination(old, to, repo_root)
        subs.append(Substitution(old=old, new=new, is_file=_is_file_path(old)))
    subs.sort(key=lambda s: len(s.old), reverse=True)
    return subs


# Leading guard: not preceded by a word char or dot (avoid ``foo.architecture``)
# and not immediately preceded by ``docs/`` (avoid double-prefixing an
# already-rewritten ``docs/architecture/...`` path — keeps the rewrite idempotent
# while still matching relative ``../architecture/...`` references).
_LEADING_GUARD = r"(?<![\w.])(?<!docs/)"
# Directory references are followed by a path separator or a prose delimiter.
_DIR_TRAILING = r"(?=[/\s\"'`)\]\},.;:>|]|$)"
# File references must not be followed by more path characters.
_FILE_TRAILING = r"(?![\w/-])"


def _compile(sub: Substitution) -> re.Pattern[str]:
    trailing = _FILE_TRAILING if sub.is_file else _DIR_TRAILING
    return re.compile(_LEADING_GUARD + re.escape(sub.old) + trailing)


def split_frontmatter(text: str) -> tuple[str, str]:
    """Split a leading YAML frontmatter block (fences included) from the body.

    Frontmatter ``fields`` (``related``/``doc_status``/``description``) are owned
    by WP12, so the body is the only region this tool rewrites.  Returns
    ``("", text)`` when there is no frontmatter.
    """

    if not text.startswith("---\n"):
        return "", text
    end = text.find("\n---", len("---\n") - 1)
    if end == -1:
        return "", text
    newline = text.find("\n", end + 1)
    cut = newline + 1 if newline != -1 else len(text)
    return text[:cut], text[cut:]


def rewrite_text(
    text: str, subs: Iterable[Substitution], *, is_markdown: bool
) -> tuple[str, int]:
    """Apply every substitution to *text*; return ``(new_text, num_rewrites)``.

    Markdown frontmatter is preserved verbatim (WP12 territory).
    """

    frontmatter, body = split_frontmatter(text) if is_markdown else ("", text)
    count = 0
    for sub in subs:
        body, num = _compile(sub).subn(sub.new, body)
        count += num
    return frontmatter + body, count


# --------------------------------------------------------------------------- #
# File traversal                                                              #
# --------------------------------------------------------------------------- #


def is_excluded(rel_path: str) -> bool:
    """True when *rel_path* (posix, repo-relative) must never be rewritten."""

    if rel_path in EXCLUDE_PATHS:
        return True
    if any(rel_path.startswith(prefix) for prefix in EXCLUDE_PREFIXES):
        return True
    if any(rel_path.startswith(prefix) for prefix in EXCLUDE_DIR_PREFIXES):
        return True
    return rel_path.rsplit("/", 1)[-1] in EXCLUDE_BASENAMES


def iter_target_files(
    repo_root: Path, roots: Iterable[str], *, include_root_md: bool = True
) -> Iterator[Path]:
    """Yield rewritable files under *roots* plus repo-root markdown files."""

    for root in roots:
        base = repo_root / root
        if not base.exists():
            continue
        for path in sorted(base.rglob("*")):
            if not path.is_file() or path.suffix not in TEXT_SUFFIXES:
                continue
            rel = path.relative_to(repo_root).as_posix()
            if not is_excluded(rel):
                yield path
    if include_root_md:
        for path in sorted(repo_root.glob("*.md")):
            if not is_excluded(path.name):
                yield path


# --------------------------------------------------------------------------- #
# Driver                                                                       #
# --------------------------------------------------------------------------- #


@dataclass
class RewriteReport:
    substitutions: list[Substitution]
    total_rewrites: int = 0
    changed_files: int = 0
    per_file: list[tuple[str, int]] = field(default_factory=list)


def run(
    repo_root: Path,
    occurrence_map_path: Path,
    roots: Iterable[str] = DEFAULT_ROOTS,
    *,
    dry_run: bool = False,
    include_root_md: bool = True,
) -> RewriteReport:
    """Execute (or plan, when *dry_run*) the bulk reference rewrite."""

    subs = build_substitutions(load_moves(occurrence_map_path), repo_root)
    report = RewriteReport(substitutions=subs)
    for path in iter_target_files(repo_root, roots, include_root_md=include_root_md):
        original = path.read_text(encoding="utf-8")
        rewritten, num = rewrite_text(
            original, subs, is_markdown=path.suffix == ".md"
        )
        if num == 0 or rewritten == original:
            continue
        report.total_rewrites += num
        report.changed_files += 1
        report.per_file.append((path.relative_to(repo_root).as_posix(), num))
        if not dry_run:
            path.write_text(rewritten, encoding="utf-8")
    return report


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root", type=Path, default=Path.cwd(), help="Repository root."
    )
    parser.add_argument(
        "--occurrence-map",
        type=Path,
        default=None,
        help=f"Occurrence map YAML (default: {DEFAULT_OCCURRENCE_MAP}).",
    )
    parser.add_argument(
        "--root",
        action="append",
        dest="roots",
        default=None,
        help="Sweep root (repeatable). Default: src tests docs.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the planned blast radius without writing.",
    )
    parser.add_argument(
        "--no-root-md",
        action="store_true",
        help="Skip repo-root *.md files.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    repo_root: Path = args.repo_root.resolve()
    occ_map = args.occurrence_map or (repo_root / DEFAULT_OCCURRENCE_MAP)
    roots = tuple(args.roots) if args.roots else DEFAULT_ROOTS

    report = run(
        repo_root,
        occ_map,
        roots,
        dry_run=args.dry_run,
        include_root_md=not args.no_root_md,
    )

    mode = "DRY-RUN" if args.dry_run else "APPLIED"
    print(f"[bulk_ref_rewrite] {mode} — {len(report.substitutions)} active substitutions")
    for sub in report.substitutions:
        print(f"  {sub.old}  ->  {sub.new}")
    print(
        f"[bulk_ref_rewrite] {mode}: "
        f"{report.total_rewrites} rewrites across {report.changed_files} files"
    )
    for rel, num in report.per_file:
        print(f"  {num:4d}  {rel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
