"""Premortem guard: the specify_cli.charter shim package must not regrow.

Contract: any file under ``src/specify_cli/charter/`` beyond the 4 known shim
files is a regression of the Mission A consolidation. This test enumerates
the directory and fails with a named, actionable diagnostic if an unknown
file appears.

Governance notes (these four points are load-bearing — reviewers verify):

1. This test is a **premortem guard** against regrowth of the legacy
   ``specify_cli.charter`` shim surface. The shim package is intentionally
   frozen at four files; anything new is a regression of the Mission A
   consolidation that moved the canonical implementation into the
   top-level ``charter`` package.
2. Adding a file here is a **per-mission decision**, not a bypass to be
   folded into an unrelated PR. New logic must travel with an updated
   ``occurrence_map.yaml`` and conscious owner review.
3. The correct location for new charter logic is ``src/charter/`` — the
   canonical owner. The shim exists solely to keep legacy
   ``from specify_cli.charter import X`` call sites resolving; it must
   not accumulate real code.
4. Loosening this test (extending ``ALLOWED_SHIM_FILES`` or relaxing the
   AST shape assertions) is a **governance change** and requires
   reviewer consensus plus a contract update. Do NOT edit this file to
   make a PR green.
"""

from __future__ import annotations

import ast
from pathlib import Path

import pytest

# Opt out of the _neutralize_worktree_detection autouse fixture in tests/conftest.py
# (which imports the full specify_cli CLI chain and fails in partial worktree
# environments). Our tests only walk the filesystem and parse AST; they do not
# need CLI worktree neutralization.
pytestmark = pytest.mark.real_worktree_detection


ALLOWED_SHIM_FILES: frozenset[str] = frozenset(
    {
        "__init__.py",
        "compiler.py",
        "interview.py",
        "resolver.py",
    }
)


def _resolve_repo_root() -> Path:
    """Resolve the repository root by walking up to the nearest pyproject.toml.

    Kept local to this test to avoid a cross-test-file fixture dependency; the
    shape is intentionally small so it can coexist with any future shared
    ``repo_root`` fixture in ``tests/conftest.py``.
    """
    here = Path(__file__).resolve()
    for candidate in (here, *here.parents):
        if (candidate / "pyproject.toml").is_file():
            return candidate
    raise RuntimeError(
        f"Could not locate pyproject.toml above {here}; repo root is unresolvable."
    )


@pytest.fixture(scope="module")
def shim_dir() -> Path:
    repo_root = _resolve_repo_root()
    d = repo_root / "src" / "specify_cli" / "charter"
    assert d.is_dir(), f"Expected shim package at {d}"
    return d


def test_no_new_files_under_shim_package(shim_dir: Path) -> None:
    """Fail if any ``.py`` file beyond ALLOWED_SHIM_FILES appears in the shim."""
    present = {p.name for p in shim_dir.iterdir() if p.is_file() and p.suffix == ".py"}
    unexpected = present - ALLOWED_SHIM_FILES
    assert not unexpected, (
        f"Unexpected file(s) under src/specify_cli/charter/: {sorted(unexpected)}.\n"
        f"The shim package is frozen at the 4 files in ALLOWED_SHIM_FILES.\n"
        f"If this file genuinely needs to exist, it belongs under src/charter/ "
        f"(the canonical owner), not under the legacy shim surface."
    )


def _assert_shim_shape(path: Path) -> None:
    """Raise AssertionError if the file contains any top-level class or function.

    The shim package is re-export-only:
      * ``compiler.py``, ``interview.py``, ``resolver.py`` are 9-line
        ``sys.modules`` aliasing shims.
      * ``__init__.py`` holds the deprecation metadata, the
        ``_warnings.warn(...)`` call, and ``from charter import ...``
        re-exports.

    In all four cases, a top-level ``ClassDef`` / ``FunctionDef`` /
    ``AsyncFunctionDef`` is a regression: real logic has leaked back into
    the shim package and must be moved to ``src/charter/``.
    """
    tree = ast.parse(path.read_text())
    for node in tree.body:
        if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            raise AssertionError(
                f"{path.name} contains a top-level {type(node).__name__} "
                f"(name={node.name!r}). The shim package must stay re-export-only; "
                f"move the definition to src/charter/."
            )


@pytest.mark.parametrize("filename", sorted(ALLOWED_SHIM_FILES))
def test_shim_file_has_no_top_level_definitions(shim_dir: Path, filename: str) -> None:
    """No ClassDef / FunctionDef / AsyncFunctionDef at module level in any shim."""
    _assert_shim_shape(shim_dir / filename)


def test_submodule_shims_alias_canonical_module(shim_dir: Path) -> None:
    """Each submodule shim must install a ``sys.modules[__name__] = ...`` alias.

    A missed alias means the re-export silently breaks: imports via
    ``specify_cli.charter.<submod>`` would not resolve to the canonical
    ``charter.<submod>``. This is cheap to check and closes the loop
    the shim-shape check leaves open (AST-level analysis cannot tell the
    difference between a no-op module and a correctly-aliased one).
    """
    for submod in ("compiler", "interview", "resolver"):
        src = (shim_dir / f"{submod}.py").read_text()
        assert f'sys.modules["charter.{submod}"]' in src or (
            f"sys.modules['charter.{submod}']" in src
        ) or (
            # Permit the common ``from charter import <submod> as _submod;
            # sys.modules[__name__] = _submod`` shape used in the repo.
            f"from charter import {submod}" in src and "sys.modules[__name__]" in src
        ), (
            f"{submod}.py does not alias the canonical charter.{submod} module. "
            f"The shim is broken — imports via specify_cli.charter.{submod} "
            f"will not resolve to the canonical module."
        )
