"""FR-005 -- charter interview answers migration + serializer hardening.

Mission ``charter-authority-flip-01M14RB3`` WP03 (T013). Two independent
concerns, five tests:

* ``scripts.migrate_charter_interview_answers.migrate_answers_file`` -- a
  standalone, defensive tool that renames a project's ``answers.yaml``
  legacy top-level governance selection key (``doctrine:``) to the
  canonical one (``charter:``), scoped to that exact key line so a
  historical proper-noun mission slug embedded in a comment (e.g.
  ``doctrine-catfooding-2196``) is never touched, and restores the
  pre-image byte-for-byte on any failure
  (``test_answers_migration_preserves_unknown_keys_and_all_answers``,
  ``test_answers_migration_preserves_selected_assets_and_template_set``,
  ``test_answers_migration_changes_only_frozen_target_bytes``,
  ``test_answers_migration_failure_restores_preimage``).
* ``charter.interview.write_interview_answers``'s ``fail_closed_on_
  regression`` opt-in -- a merge-then-guard serializer that preserves keys
  ``CharterInterview`` does not model and refuses to persist a change that
  would drop an answer or reset a known selection to empty
  (``test_interview_serializer_round_trips_extended_answers``).
"""

from __future__ import annotations

from dataclasses import replace
from pathlib import Path

import pytest
from ruamel.yaml import YAML

from charter.interview import (
    InterviewAnswersRegressionError,
    read_interview_answers,
    write_interview_answers,
)
from scripts.migrate_charter_interview_answers import (
    AnswersMigrationError,
    migrate_answers_file,
)
import scripts.migrate_charter_interview_answers as migrate_module

pytestmark = pytest.mark.fast


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

#: A legacy ``answers.yaml`` nesting the governance selection under the
#: retired top-level ``doctrine:`` key, carrying the frozen proper-noun
#: comment slug (occurrence_map.yaml's ``comments:doctrine-catfooding-2196``
#: exception -- NOT the governing term, must survive untouched), unknown
#: keys the migration has no business understanding, and a populated
#: ``answers`` block.
_LEGACY_NESTED_FIXTURE = """\
# Charter interview answers
# Generated by WP13 (doctrine-catfooding-2196-01KWE16N) capstone compile.
# Mirrors the activated catfooding doctrine set; do not edit manually.

mission: software-dev
profile: minimal

answers:
  project_intent: >
    Some project intent text.
  testing_requirements: >
    Some testing requirements text.

doctrine:
  selected_paradigms: []
  selected_directives:
    - DIRECTIVE_001
    - DIRECTIVE_003
  selected_tactics:
    - tdd-red-green-refactor
  selected_styleguides:
    - python-conventions
  selected_toolguides:
    - git-agent-commit-signing
  selected_procedures:
    - disciplined-defect-diagnosis
  selected_assets:
    - project-glossary
  available_tools:
    - git
    - pytest
  template_set: software-dev-default

custom_unknown_key: some-value
"""


def _write_fixture(tmp_path: Path, content: str = _LEGACY_NESTED_FIXTURE) -> Path:
    path = tmp_path / "answers.yaml"
    path.write_text(content, encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Migration script
# ---------------------------------------------------------------------------


def test_answers_migration_preserves_unknown_keys_and_all_answers(tmp_path: Path) -> None:
    path = _write_fixture(tmp_path)
    before = YAML(typ="safe").load(path.read_text(encoding="utf-8"))

    renamed = migrate_answers_file(path)

    assert renamed == 1
    after = YAML(typ="safe").load(path.read_text(encoding="utf-8"))

    # Every answer survives untouched.
    assert after["answers"] == before["answers"]
    # The unknown key the migration has no schema knowledge of survives.
    assert after["custom_unknown_key"] == before["custom_unknown_key"] == "some-value"
    assert after["mission"] == before["mission"]
    assert after["profile"] == before["profile"]


def test_answers_migration_preserves_selected_assets_and_template_set(tmp_path: Path) -> None:
    path = _write_fixture(tmp_path)

    migrate_answers_file(path)

    after = YAML(typ="safe").load(path.read_text(encoding="utf-8"))
    assert "doctrine" not in after
    assert after["charter"]["selected_assets"] == ["project-glossary"]
    assert after["charter"]["template_set"] == "software-dev-default"
    assert after["charter"]["selected_styleguides"] == ["python-conventions"]


def test_answers_migration_changes_only_frozen_target_bytes(tmp_path: Path) -> None:
    path = _write_fixture(tmp_path)
    before_lines = path.read_text(encoding="utf-8").splitlines()

    renamed = migrate_answers_file(path)

    assert renamed == 1
    after_lines = path.read_text(encoding="utf-8").splitlines()
    assert len(before_lines) == len(after_lines)

    diffs = [
        (before_line, after_line)
        for before_line, after_line in zip(before_lines, after_lines, strict=True)
        if before_line != after_line
    ]
    assert diffs == [("doctrine:", "charter:")]

    # The frozen proper-noun mission slug is byte-identical, line for line.
    slug_lines_before = [line for line in before_lines if "doctrine-catfooding-2196" in line]
    slug_lines_after = [line for line in after_lines if "doctrine-catfooding-2196" in line]
    assert slug_lines_before  # sanity: fixture actually carries the slug
    assert slug_lines_before == slug_lines_after


def test_answers_migration_failure_restores_preimage(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    path = _write_fixture(tmp_path)
    preimage = path.read_bytes()

    def _boom(_path: Path, _data: bytes) -> None:
        raise OSError("simulated disk failure mid-migration")

    monkeypatch.setattr(migrate_module, "_write_bytes", _boom)

    with pytest.raises(AnswersMigrationError):
        migrate_module.migrate_answers_file(path)

    assert path.read_bytes() == preimage


def test_migration_leaves_canonical_only_file_byte_identical(tmp_path: Path) -> None:
    """A file already on the canonical key (no legacy occurrence) is a no-op."""
    content = _LEGACY_NESTED_FIXTURE.replace("doctrine:\n", "charter:\n", 1)
    path = _write_fixture(tmp_path, content)
    preimage = path.read_bytes()

    renamed = migrate_answers_file(path)

    assert renamed == 0
    assert path.read_bytes() == preimage


def test_migration_does_not_touch_slug_when_no_legacy_key_present(tmp_path: Path) -> None:
    """The comment slug alone (no top-level ``doctrine:`` key) never matches."""
    content = (
        "# Generated by WP13 (doctrine-catfooding-2196-01KWE16N) capstone compile.\n"
        "mission: software-dev\n"
        "profile: minimal\n"
        "answers: {}\n"
    )
    path = _write_fixture(tmp_path, content)
    preimage = path.read_bytes()

    renamed = migrate_answers_file(path)

    assert renamed == 0
    assert path.read_bytes() == preimage


# ---------------------------------------------------------------------------
# Interview serializer hardening
# ---------------------------------------------------------------------------

_EXTENDED_FLAT_FIXTURE = """\
mission: software-dev
profile: minimal

answers:
  project_intent: >
    Some project intent text.

selected_paradigms: []
selected_directives:
  - DIRECTIVE_001
selected_tactics:
  - tdd-red-green-refactor
available_tools:
  - git
  - pytest

selected_styleguides:
  - python-conventions
selected_toolguides:
  - git-agent-commit-signing
selected_procedures:
  - disciplined-defect-diagnosis
template_set: software-dev-default
custom_unknown_key: keep-me
"""


def test_interview_serializer_round_trips_extended_answers(tmp_path: Path) -> None:
    path = tmp_path / "answers.yaml"
    path.write_text(_EXTENDED_FLAT_FIXTURE, encoding="utf-8")

    interview = read_interview_answers(path)
    assert interview is not None
    assert interview.selected_tactics == ["tdd-red-green-refactor"]

    # Positive: writing the interview back unmodified preserves every
    # extended/unknown key this dataclass does not itself model.
    write_interview_answers(path, interview, fail_closed_on_regression=True)
    reloaded = YAML(typ="safe").load(path.read_text(encoding="utf-8"))
    assert reloaded["selected_styleguides"] == ["python-conventions"]
    assert reloaded["selected_toolguides"] == ["git-agent-commit-signing"]
    assert reloaded["selected_procedures"] == ["disciplined-defect-diagnosis"]
    assert reloaded["template_set"] == "software-dev-default"
    assert reloaded["custom_unknown_key"] == "keep-me"
    assert reloaded["answers"]["project_intent"].strip() == "Some project intent text."

    # Negative: deleting a previously-answered question fails closed.
    deleted_answer = replace(
        interview,
        answers={k: v for k, v in interview.answers.items() if k != "project_intent"},
    )
    with pytest.raises(InterviewAnswersRegressionError):
        write_interview_answers(path, deleted_answer, fail_closed_on_regression=True)

    # Negative: default-reset of a known selection list fails closed.
    reset_directives = replace(interview, selected_directives=[])
    with pytest.raises(InterviewAnswersRegressionError):
        write_interview_answers(path, reset_directives, fail_closed_on_regression=True)

    # Negative: emptying selected_tactics specifically fails closed.
    reset_tactics = replace(interview, selected_tactics=[])
    with pytest.raises(InterviewAnswersRegressionError):
        write_interview_answers(path, reset_tactics, fail_closed_on_regression=True)

    # The file on disk is untouched by the rejected writes above.
    still_reloaded = YAML(typ="safe").load(path.read_text(encoding="utf-8"))
    assert still_reloaded["selected_styleguides"] == ["python-conventions"]

    # Without the opt-in, the writer stays permissive (default production
    # behavior for the interactive interview flow, which legitimately
    # narrows selections session to session) -- but STILL preserves the
    # unmodeled extended keys via the unconditional merge.
    write_interview_answers(path, reset_tactics)
    permissive_reload = YAML(typ="safe").load(path.read_text(encoding="utf-8"))
    assert permissive_reload["selected_tactics"] == []
    assert permissive_reload["selected_styleguides"] == ["python-conventions"]
