"""Runtime bootstrap wrapper scripts for the Claude Code plugin bundle (WP05).

Generates the ``bin/spec-kitty-wrapper`` (bash) and ``bin/spec-kitty-wrapper.cmd``
(Windows CMD) scripts that Claude Code invokes when executing a Spec Kitty skill.

Both wrappers implement the same two-step runtime fallback:

1. If ``spec-kitty`` is on PATH and reachable, delegate directly (fast path for
   users who have the CLI installed).
2. If ``uvx`` is on PATH, run ``uvx spec-kitty-cli=={VERSION}`` (fallback for
   users who only have ``uv`` installed).
3. If neither is available, print a helpful error and exit 1.

``__SPEC_KITTY_VERSION__`` is substituted with the real version string at build
time by :func:`write_wrappers`.  The wrapper files are generated artefacts and
are **not** committed to the source repository — they live only under the
caller-supplied ``bundle_dir``.

**Scope guard (FR-016, C-006):** This module only writes to the
``bin/`` subdirectory of the caller-supplied ``bundle_dir``.  It never installs,
registers, enables, or publishes the bundle.
"""

from __future__ import annotations

import stat
from pathlib import Path


# Placeholder that is substituted at build time with the real package version.
_VERSION_PLACEHOLDER = "__SPEC_KITTY_VERSION__"

# Template for the bash wrapper script.
_BASH_WRAPPER_TEMPLATE = """\
#!/usr/bin/env bash
# Spec Kitty runtime bootstrap — PATH-check with uvx fallback.
# Generated by spec-kitty plugin build. Do not edit manually.
set -euo pipefail

VERSION="{version}"

if command -v spec-kitty >/dev/null 2>&1 && spec-kitty --version >/dev/null 2>&1; then
    exec spec-kitty "$@"
fi

if command -v uvx >/dev/null 2>&1; then
    exec uvx "spec-kitty-cli==${{VERSION}}" "$@"
fi

echo "Error: spec-kitty is not installed and uvx is not available." >&2
echo "Install spec-kitty: pip install spec-kitty-cli" >&2
exit 1
"""

# Template for the Windows CMD wrapper script.
#
# EXIT /B %ERRORLEVEL% must never sit inside a parenthesized IF block: cmd.exe
# expands %VAR% in a compound statement at parse time, so it would capture the
# errorlevel left by the preceding `where` probe (always 0 on the branch taken)
# rather than the errorlevel `spec-kitty`/`uvx` actually returned. GOTO keeps
# each EXIT /B outside any parentheses so the expansion happens at runtime.
_CMD_WRAPPER_TEMPLATE = """\
@echo off
REM Spec Kitty runtime bootstrap for Windows.
REM Generated by spec-kitty plugin build. Do not edit manually.
SET VERSION={version}

where spec-kitty >nul 2>&1
IF ERRORLEVEL 1 GOTO try_uvx
CALL spec-kitty --version >nul 2>&1
IF ERRORLEVEL 1 GOTO try_uvx
spec-kitty %*
EXIT /B %ERRORLEVEL%

:try_uvx
where uvx >nul 2>&1
IF ERRORLEVEL 1 GOTO no_runtime
uvx spec-kitty-cli==%VERSION% %*
EXIT /B %ERRORLEVEL%

:no_runtime
echo Error: spec-kitty is not installed and uvx is not available.
echo Install spec-kitty: pip install spec-kitty-cli
EXIT /B 1
"""

# Owner-only rwx bits for a local executable file.
_EXECUTABLE_MODE = stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR


def write_wrappers(
    bundle_dir: Path, version: str | None = None, *, prepared: tuple[Path, bytes, int] | None = None,
) -> None:
    """Write ``bin/spec-kitty-wrapper`` and ``bin/spec-kitty-wrapper.cmd``.

    Both files are generated under ``bundle_dir / "bin"`` with ``version``
    substituted for :data:`_VERSION_PLACEHOLDER`.  The bash script is made
    owner-executable (mode 700); Windows filesystem permissions are unchanged.

    Parameters
    ----------
    bundle_dir:
        Root of the plugin bundle (e.g. ``dist/spec-kitty-plugins/claude-code/``).
    version:
        The resolved package version string (e.g. ``"3.2.0"``).  Must be a
        non-empty string; the caller is responsible for validation.

    Raises
    ------
    ValueError
        When *version* is empty.
    """
    if prepared is not None:
        from .projection import observe_confined, write_staged_file

        path, content, mode = prepared
        if path not in {bundle_dir / "bin/spec-kitty-wrapper", bundle_dir / "bin/spec-kitty-wrapper.cmd"}:
            raise ValueError("Prepared wrapper destination is outside the wrapper layout")
        observe_confined(bundle_dir, path)
        write_staged_file(path, content, mode)
        return
    if not version:
        raise ValueError("version must be a non-empty string")

    from ..operations import ApplyConsent, AssessmentInputs
    from ._builder import finish_build
    from .model import StagedFile
    from .projection import confined_output, prepare_staging, staging_root

    root = staging_root(bundle_dir)
    directory = confined_output(bundle_dir, root)
    inputs = AssessmentInputs(root, consent=ApplyConsent(automatic=True))
    files = (
        StagedFile((directory / "bin/spec-kitty-wrapper").relative_to(root.path).as_posix(),
                   wrapper_bash_content(version).encode("utf-8"), _EXECUTABLE_MODE, wrapper=True),
        StagedFile((directory / "bin/spec-kitty-wrapper.cmd").relative_to(root.path).as_posix(),
                   wrapper_cmd_content(version).encode("utf-8"), wrapper=True),
    )
    finish_build(prepare_staging(inputs, files, ()))


def wrapper_bash_content(version: str) -> str:
    """Return the rendered bash wrapper content for *version*.

    Useful for inspection and testing without touching the filesystem.
    """
    return _BASH_WRAPPER_TEMPLATE.format(version=version)


def wrapper_cmd_content(version: str) -> str:
    """Return the rendered Windows CMD wrapper content for *version*.

    Useful for inspection and testing without touching the filesystem.
    """
    return _CMD_WRAPPER_TEMPLATE.format(version=version)


# Content helpers are consumed during preparation; write_wrappers also accepts
# one retained member during guarded batch application without rendering again.
__all__ = [
    "write_wrappers",
]
