"""Structured WP manifest reader for wps.yaml.

Provides the canonical data model, YAML loader, and tasks.md generator
for spec-kitty missions that use wps.yaml as their primary WP source.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field, PrivateAttr, field_validator


class WorkPackageEntry(BaseModel):
    """One work package entry in wps.yaml."""

    id: str  # e.g. "WP01" — validated as WPnn pattern
    title: str
    dependencies: list[str] = Field(default_factory=list)
    owned_files: list[str] = Field(default_factory=list)
    requirement_refs: list[str] = Field(default_factory=list)
    subtasks: list[str] = Field(default_factory=list)
    prompt_file: str | None = None

    # Internal: True when 'dependencies' key was present in the source YAML.
    # Set by load_wps_manifest(); NOT part of the serialized schema.
    _dependencies_explicit: bool = PrivateAttr(default=False)

    @field_validator("id")
    @classmethod
    def validate_id(cls, v: str) -> str:
        if not re.match(r"^WP\d{2}$", v):
            raise ValueError(f"WP id must be WPnn (e.g. WP01), got: {v!r}")
        return v

    @field_validator("dependencies")
    @classmethod
    def validate_dependencies(cls, v: list[str]) -> list[str]:
        for dep in v:
            if not re.match(r"^WP\d{2}$", dep):
                raise ValueError(f"Dependency must be WPnn (e.g. WP01), got: {dep!r}")
        return v


class WpsManifest(BaseModel):
    """Top-level wps.yaml manifest."""

    work_packages: list[WorkPackageEntry]


def load_wps_manifest(feature_dir: Path) -> WpsManifest | None:
    """Load wps.yaml from feature_dir if present.

    Returns None if wps.yaml does not exist (legacy mission — use prose parser).
    Raises pydantic.ValidationError if the file exists but is malformed,
    with the failing field name and value in the error message.

    Args:
        feature_dir: Path to the kitty-specs/<mission>/ directory.
    """
    wps_path = feature_dir / "wps.yaml"
    if not wps_path.exists():
        return None

    from ruamel.yaml import YAML

    yaml = YAML(typ="safe")
    raw: dict[str, Any] = yaml.load(wps_path)

    # Track explicit dependencies before Pydantic validation
    wps_raw: list[dict[str, Any]] = raw.get("work_packages", [])
    manifest = WpsManifest.model_validate(raw)

    # Back-fill _dependencies_explicit on each entry using PrivateAttr mechanism
    for entry, raw_wp in zip(manifest.work_packages, wps_raw):
        object.__setattr__(entry, "_dependencies_explicit", "dependencies" in raw_wp)

    return manifest


def dependencies_are_explicit(entry: WorkPackageEntry) -> bool:
    """Return True if the 'dependencies' key was present in the source YAML.

    When True, the pipeline must not overwrite or augment the value.
    When False, the field was absent from YAML and may be populated by tasks-packages.
    """
    return getattr(entry, "_dependencies_explicit", False)


def generate_tasks_md_from_manifest(manifest: WpsManifest, feature_name: str) -> str:
    """Generate tasks.md content from a WpsManifest.

    Output is a human-readable markdown document following tasks-template.md
    conventions. Does NOT include implementation notes or risks — those live
    in the WP prompt files.

    Args:
        manifest: Loaded WpsManifest.
        feature_name: Mission slug or friendly name for the heading.
    """
    lines: list[str] = [
        f"# Work Packages: {feature_name}",
        "",
        "_Generated by finalize-tasks from wps.yaml. Do not edit directly._",
        "",
        "---",
        "",
    ]

    for wp in manifest.work_packages:
        lines.append(f"## Work Package {wp.id}: {wp.title}")
        lines.append("")

        if wp.dependencies:
            lines.append(f"**Dependencies**: {', '.join(wp.dependencies)}")
        else:
            lines.append("**Dependencies**: None")

        if wp.requirement_refs:
            lines.append(f"**Requirement Refs**: {', '.join(wp.requirement_refs)}")

        if wp.owned_files:
            lines.append(f"**Owned Files**: {', '.join(wp.owned_files)}")

        if wp.subtasks:
            lines.append(f"**Subtasks**: {', '.join(wp.subtasks)}")

        if wp.prompt_file:
            lines.append(f"**Prompt**: `{wp.prompt_file}`")

        lines.append("")
        lines.append("---")
        lines.append("")

    return "\n".join(lines)
