"""Migration 3.1.2: Remove project-level spec-kitty command files.

As of 3.1.2, slash commands (spec-kitty.*.md, spec-kitty.*.toml, etc.) are
installed globally to the user's home agent directories (``~/.claude/commands/``,
``~/.gemini/commands/``, etc.) by ``ensure_global_agent_commands()`` at CLI
startup.  Per-project copies in ``.claude/commands/``, ``.gemini/commands/``,
etc. are no longer generated by ``spec-kitty init`` and are no longer needed.

This migration removes any ``spec-kitty.*`` files found in the configured agent
command directories of the consumer project.  Non-spec-kitty files are left
untouched.

Idempotency
-----------
A project with no ``spec-kitty.*`` command files returns ``detect() == False``
and is skipped by the runner without any file system changes.
"""

from __future__ import annotations

from pathlib import Path

from ..registry import MigrationRegistry
from .base import BaseMigration, MigrationResult
from .m_0_9_1_complete_lane_migration import get_agent_dirs_for_project


@MigrationRegistry.register
class GlobalizeCommandsMigration(BaseMigration):
    """Remove per-project spec-kitty command files (now installed globally)."""

    migration_id = "3.1.2_globalize_commands"
    description = "Remove per-project spec-kitty command files (now installed globally to ~/.agent-dir/)"
    target_version = "3.1.2"

    def detect(self, project_path: Path) -> bool:
        """Return True if any spec-kitty.* command file exists in any agent command dir."""
        for agent_root, subdir in get_agent_dirs_for_project(project_path):
            agent_dir = project_path / agent_root / subdir
            if not agent_dir.is_dir():
                continue
            for f in agent_dir.iterdir():
                if f.name.startswith("spec-kitty."):
                    return True
        return False

    def can_apply(self, project_path: Path) -> tuple[bool, str]:
        return True, ""

    def apply(self, project_path: Path, dry_run: bool = False) -> MigrationResult:
        changes: list[str] = []

        for agent_root, subdir in get_agent_dirs_for_project(project_path):
            agent_dir = project_path / agent_root / subdir
            if not agent_dir.is_dir():
                continue

            targets = sorted(f for f in agent_dir.iterdir() if f.name.startswith("spec-kitty."))
            for target in targets:
                rel = target.relative_to(project_path)
                if dry_run:
                    changes.append(f"Would remove: {rel}")
                else:
                    try:
                        # Files may be read-only (written with chmod ~0o222)
                        target.chmod(target.stat().st_mode | 0o222)
                        target.unlink()
                        changes.append(f"Removed: {rel}")
                    except OSError as exc:
                        changes.append(f"Could not remove {rel}: {exc}")

            # Best-effort: remove the directory if it's now empty.
            if not dry_run and agent_dir.is_dir():
                try:
                    agent_dir.rmdir()
                    changes.append(f"Removed empty directory: {agent_dir.relative_to(project_path)}")
                except OSError:
                    pass  # Non-empty or permission error — leave it

        return MigrationResult(success=True, changes_made=changes)
