"""Tests for provenance.py — WP03 T015 / T020.

Covers:
- Pydantic round-trip (dump_yaml → load_yaml → field-by-field compare)
- allOf validator: rejects entries with neither source_section nor non-empty
  source_urns
- Byte-reproducibility of dump_yaml under fixed inputs (NFR-006)
- artifact_content_hash matches hash of bytes written by dump_yaml
"""

from __future__ import annotations

import hashlib
from pathlib import Path

import pytest
from pydantic import ValidationError

from charter.synthesizer.provenance import ProvenanceEntry, dump_yaml, load_yaml
from charter.synthesizer.path_guard import PathGuard
from charter.synthesizer.synthesize_pipeline import canonical_yaml


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def guard(tmp_path: Path) -> PathGuard:
    """PathGuard allowing writes to tmp_path."""
    return PathGuard(tmp_path, extra_allowed_prefixes=[tmp_path])


@pytest.fixture
def sample_provenance() -> ProvenanceEntry:
    """A fully-populated ProvenanceEntry for testing."""
    return ProvenanceEntry(
        schema_version="1",
        artifact_urn="tactic:how-we-apply-directive-003",
        artifact_kind="tactic",
        artifact_slug="how-we-apply-directive-003",
        artifact_content_hash="a" * 64,
        inputs_hash="b" * 64,
        adapter_id="fixture",
        adapter_version="1.0.0",
        source_section=None,
        source_urns=["directive:DIRECTIVE_003"],
        generated_at="2026-04-17T12:00:00+00:00",
        adapter_notes=None,
    )


@pytest.fixture
def sample_directive_provenance() -> ProvenanceEntry:
    """A ProvenanceEntry for a directive with source_section set."""
    return ProvenanceEntry(
        schema_version="1",
        artifact_urn="directive:project-decision-doc",
        artifact_kind="directive",
        artifact_slug="project-decision-doc",
        artifact_content_hash="c" * 64,
        inputs_hash="d" * 64,
        adapter_id="fixture",
        adapter_version="1.0.0",
        source_section="testing_philosophy",
        source_urns=[],
        generated_at="2026-04-17T12:00:00+00:00",
        adapter_notes="Generated by fixture adapter",
    )


# ---------------------------------------------------------------------------
# Round-trip test
# ---------------------------------------------------------------------------


def test_round_trip_with_source_urns(
    tmp_path: Path, guard: PathGuard, sample_provenance: ProvenanceEntry
) -> None:
    """dump_yaml → load_yaml reproduces all fields exactly."""
    out_path = tmp_path / "tactic-how-we-apply-directive-003.yaml"
    dump_yaml(sample_provenance, out_path, guard)
    assert out_path.exists()

    loaded = load_yaml(out_path)

    assert loaded.schema_version == sample_provenance.schema_version
    assert loaded.artifact_urn == sample_provenance.artifact_urn
    assert loaded.artifact_kind == sample_provenance.artifact_kind
    assert loaded.artifact_slug == sample_provenance.artifact_slug
    assert loaded.artifact_content_hash == sample_provenance.artifact_content_hash
    assert loaded.inputs_hash == sample_provenance.inputs_hash
    assert loaded.adapter_id == sample_provenance.adapter_id
    assert loaded.adapter_version == sample_provenance.adapter_version
    assert loaded.source_section == sample_provenance.source_section
    assert loaded.source_urns == sample_provenance.source_urns
    assert loaded.generated_at == sample_provenance.generated_at
    assert loaded.adapter_notes == sample_provenance.adapter_notes


def test_round_trip_with_source_section(
    tmp_path: Path, guard: PathGuard, sample_directive_provenance: ProvenanceEntry
) -> None:
    """Provenance with source_section (no source_urns) round-trips correctly."""
    out_path = tmp_path / "directive-project-decision-doc.yaml"
    dump_yaml(sample_directive_provenance, out_path, guard)
    loaded = load_yaml(out_path)
    assert loaded.source_section == "testing_philosophy"
    assert loaded.source_urns == []
    assert loaded.adapter_notes == "Generated by fixture adapter"


# ---------------------------------------------------------------------------
# allOf validator: at least one of source_section or non-empty source_urns
# ---------------------------------------------------------------------------


def test_allof_validator_rejects_neither() -> None:
    """ProvenanceEntry with both source_section=None and source_urns=[] is invalid."""
    with pytest.raises(ValidationError) as exc_info:
        ProvenanceEntry(
            schema_version="1",
            artifact_urn="tactic:bad-tactic",
            artifact_kind="tactic",
            artifact_slug="bad-tactic",
            artifact_content_hash="a" * 64,
            inputs_hash="b" * 64,
            adapter_id="fixture",
            adapter_version="1.0.0",
            source_section=None,   # neither set
            source_urns=[],        # nor this
            generated_at="2026-04-17T12:00:00+00:00",
        )
    # Should mention the allOf / source constraint
    assert exc_info.value is not None


def test_allof_validator_accepts_source_section_only() -> None:
    """ProvenanceEntry with source_section set (empty source_urns) is valid."""
    entry = ProvenanceEntry(
        schema_version="1",
        artifact_urn="directive:my-directive",
        artifact_kind="directive",
        artifact_slug="my-directive",
        artifact_content_hash="a" * 64,
        inputs_hash="b" * 64,
        adapter_id="fixture",
        adapter_version="1.0.0",
        source_section="testing_philosophy",
        source_urns=[],
        generated_at="2026-04-17T12:00:00+00:00",
    )
    assert entry.source_section == "testing_philosophy"


def test_allof_validator_accepts_source_urns_only() -> None:
    """ProvenanceEntry with non-empty source_urns (no source_section) is valid."""
    entry = ProvenanceEntry(
        schema_version="1",
        artifact_urn="tactic:my-tactic",
        artifact_kind="tactic",
        artifact_slug="my-tactic",
        artifact_content_hash="a" * 64,
        inputs_hash="b" * 64,
        adapter_id="fixture",
        adapter_version="1.0.0",
        source_section=None,
        source_urns=["directive:DIRECTIVE_003"],
        generated_at="2026-04-17T12:00:00+00:00",
    )
    assert entry.source_urns == ["directive:DIRECTIVE_003"]


# ---------------------------------------------------------------------------
# Byte-reproducibility (NFR-006)
# ---------------------------------------------------------------------------


def test_dump_yaml_byte_reproducibility(
    tmp_path: Path, guard: PathGuard, sample_provenance: ProvenanceEntry
) -> None:
    """Two dump_yaml calls with identical input produce byte-identical files."""
    path1 = tmp_path / "prov1.yaml"
    path2 = tmp_path / "prov2.yaml"
    dump_yaml(sample_provenance, path1, guard)
    dump_yaml(sample_provenance, path2, guard)
    assert path1.read_bytes() == path2.read_bytes()


def test_dump_yaml_hash_matches_canonical_yaml(
    tmp_path: Path, guard: PathGuard, sample_provenance: ProvenanceEntry
) -> None:
    """artifact_content_hash computed via canonical_yaml matches dump_yaml bytes.

    This test validates that WP02's content hash (canonical_yaml → sha256) is
    byte-stable with WP03's on-disk serialization (dump_yaml uses canonical_yaml).
    """
    # Simulate the WP02 artifact body that would be written for this provenance.
    body = {
        "id": "HOW_003",
        "title": "How to apply directive 003",
        "summary": "A summary.",
    }
    artifact_bytes = canonical_yaml(body)
    expected_hash = hashlib.sha256(artifact_bytes).hexdigest()

    # Build a provenance entry with the matching content hash
    prov = ProvenanceEntry(
        schema_version="1",
        artifact_urn="tactic:how-we-apply-directive-003",
        artifact_kind="tactic",
        artifact_slug="how-we-apply-directive-003",
        artifact_content_hash=expected_hash,
        inputs_hash="b" * 64,
        adapter_id="fixture",
        adapter_version="1.0.0",
        source_section=None,
        source_urns=["directive:DIRECTIVE_003"],
        generated_at="2026-04-17T12:00:00+00:00",
    )

    out_path = tmp_path / "tactic-how-we-apply-directive-003.yaml"
    dump_yaml(prov, out_path, guard)
    loaded = load_yaml(out_path)

    # The content hash in the loaded provenance matches the canonical_yaml hash
    assert loaded.artifact_content_hash == expected_hash
