"""Charter Synthesizer orchestrator — public entrypoints.

This module owns the top-level entry points for the synthesizer pipeline:
- synthesize(request) → SynthesisResult
- resynthesize(request, topic) → SynthesisResult

Both functions use lazy imports to delegate to their respective pipeline
modules. This keeps WP01's tests independent of WP02/WP05 implementations
while preserving a clean ownership boundary: downstream WPs deliver their
pipeline modules; they do NOT edit this file.

Adapter injection
-----------------
Both entry points accept an optional `adapter` argument. When not supplied,
the production adapter is selected (WP05 / CLI wiring — outside WP01 scope).
Tests pass a FixtureAdapter instance explicitly.

WP02 pipeline (synthesize_pipeline.py) is owned by WP02.
WP05 pipeline (resynthesize_pipeline.py) is owned by WP05.

See plan.md §KD-1, §KD-6.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

    from .adapter import AdapterOutput, SynthesisAdapter
    from .request import SynthesisRequest


# ---------------------------------------------------------------------------
# Result type (owned by WP01; WP02 populates fields)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SynthesisResult:
    """Per-target result assembled by the synthesis pipeline.

    Fields are populated by WP02 (synthesize_pipeline.py). WP01 defines the
    type so downstream WPs share a common output contract.
    """

    target_kind: str
    target_slug: str
    adapter_output: AdapterOutput
    """Raw adapter output; orchestration validates and writes it."""

    inputs_hash: str
    """Full SHA-256 hex digest of the normalized SynthesisRequest."""

    effective_adapter_id: str
    """adapter_id_override if set; else adapter.id."""

    effective_adapter_version: str
    """adapter_version_override if set; else adapter.version."""


def _shipped_drg_from_snapshot(snapshot: object) -> object:
    """Normalize a request DRG snapshot into a validate-able DRGGraph payload."""
    if not isinstance(snapshot, dict):
        return snapshot

    normalized = dict(snapshot)
    normalized.setdefault("nodes", [])
    normalized.setdefault("edges", [])
    normalized["schema_version"] = "1.0"
    normalized.setdefault("generated_at", "1970-01-01T00:00:00+00:00")
    normalized.setdefault("generated_by", "request.drg_snapshot")
    return normalized


# ---------------------------------------------------------------------------
# Public entry points
# ---------------------------------------------------------------------------


def synthesize(
    request: SynthesisRequest,
    adapter: SynthesisAdapter | None = None,
    repo_root: Path | None = None,
) -> SynthesisResult:
    """Run the full synthesis pipeline for a single SynthesisRequest.

    Delegates to synthesize_pipeline.run_all() (WP02), then stages and
    promotes all artifacts to disk via write_pipeline.promote() (WP03, T018).
    The lazy-import seam resolves: write_pipeline.promote() now has a
    production caller.

    Parameters
    ----------
    request:
        The fully-populated SynthesisRequest envelope.
    adapter:
        The adapter to use for generation. When None, the production adapter
        is resolved (WP05 / CLI wiring). Tests pass a FixtureAdapter.
    repo_root:
        Repository root for staging/promote. Inferred from CWD when None
        (WP05 / CLI wiring will supply this explicitly).

    Returns
    -------
    SynthesisResult
        Per-target result with validated artifact body + provenance fields.
        The manifest + artifacts have been written to disk before returning.

    Raises
    ------
    NotImplementedError
        Until WP02 delivers synthesize_pipeline.py (pre-WP02 state).
    ImportError
        Propagated if synthesize_pipeline or write_pipeline module is missing.
    """
    from pathlib import Path as _Path  # noqa: PLC0415

    try:
        from doctrine.drg.models import DRGGraph as _DRGGraph  # noqa: PLC0415
        from importlib.metadata import version as _pkg_version  # noqa: PLC0415

        _SPEC_KITTY_VERSION = _pkg_version("spec-kitty-cli")
        from .interview_mapping import resolve_sections as _resolve_sections  # noqa: PLC0415
        from .project_drg import emit_project_layer as _emit_project_layer  # noqa: PLC0415
        from .project_drg import persist as _persist_project_graph  # noqa: PLC0415
        from .synthesize_pipeline import run_all as _run_all  # noqa: PLC0415
        from .staging import StagingDir as _StagingDir  # noqa: PLC0415
        from .targets import build_targets as _build_targets  # noqa: PLC0415
        from .targets import detect_duplicates as _detect_duplicates  # noqa: PLC0415
        from .targets import order_targets as _order_targets  # noqa: PLC0415
        from .validation_gate import validate as _validate_project_graph  # noqa: PLC0415
        from . import write_pipeline as _write_pipeline  # noqa: PLC0415
    except ImportError as exc:
        raise NotImplementedError(
            "synthesize() is not yet fully implemented — WP02 must deliver synthesize_pipeline.py and WP03 must deliver write_pipeline.py."
        ) from exc

    # --- In-memory pipeline (WP02) ---
    results = _run_all(request, adapter=adapter)

    shipped_drg = _DRGGraph.model_validate(_shipped_drg_from_snapshot(request.drg_snapshot))
    sections = _resolve_sections(request.interview_snapshot)
    targets = _build_targets(
        interview_snapshot=dict(request.interview_snapshot),
        mappings=sections,
        drg_snapshot=dict(request.drg_snapshot),
    )
    targets = _order_targets(targets)
    _detect_duplicates(targets)
    if not targets:
        targets = [request.target]

    def _validation_callback(staged_dir: _StagingDir) -> None:
        project_graph = _emit_project_layer(
            targets=targets,
            spec_kitty_version=_SPEC_KITTY_VERSION,
            shipped_drg=shipped_drg,
        )
        _persist_project_graph(project_graph, staged_dir.root, staged_dir.guard)
        _validate_project_graph(staged_dir.root, shipped_drg)

    # --- Stage and promote to disk (WP03, T018) ---
    _repo_root = repo_root if repo_root is not None else _Path.cwd()
    with _StagingDir.create(_repo_root, request.run_id) as staging_dir:
        _write_pipeline.promote(
            request,
            staging_dir,
            results,
            _validation_callback,
        )

    # --- Reconstruct SynthesisResult for the primary target ---
    from datetime import datetime  # noqa: PLC0415
    from .adapter import AdapterOutput as _AdapterOutput  # noqa: PLC0415

    primary_target = request.target
    for body, prov in results:
        if prov.artifact_kind == primary_target.kind and prov.artifact_slug == primary_target.slug:
            return SynthesisResult(
                target_kind=prov.artifact_kind,
                target_slug=prov.artifact_slug,
                adapter_output=_AdapterOutput(
                    body=body,
                    generated_at=datetime.fromisoformat(prov.generated_at) if not isinstance(prov.generated_at, datetime) else prov.generated_at,
                ),
                inputs_hash=prov.inputs_hash,
                effective_adapter_id=prov.adapter_id,
                effective_adapter_version=prov.adapter_version,
            )

    # Fallback to first result if primary target was not among synthesized targets
    first_body, first_prov = results[0]
    return SynthesisResult(
        target_kind=first_prov.artifact_kind,
        target_slug=first_prov.artifact_slug,
        adapter_output=_AdapterOutput(
            body=first_body,
            generated_at=datetime.fromisoformat(first_prov.generated_at) if not isinstance(first_prov.generated_at, datetime) else first_prov.generated_at,
        ),
        inputs_hash=first_prov.inputs_hash,
        effective_adapter_id=first_prov.adapter_id,
        effective_adapter_version=first_prov.adapter_version,
    )


def resynthesize(
    request: SynthesisRequest,
    topic: str,
    adapter: SynthesisAdapter | None = None,
) -> SynthesisResult:
    """Run bounded resynthesis for a single structured topic selector.

    Delegates to resynthesize_pipeline.run() (implemented in WP05).

    Parameters
    ----------
    request:
        The SynthesisRequest for the targeted artifact.
    topic:
        Structured selector string (kind:slug | DRG URN | interview section).
    adapter:
        Adapter to use. None → production adapter (WP05 CLI wiring).

    Returns
    -------
    SynthesisResult
        Result for the targeted artifact.

    Raises
    ------
    NotImplementedError
        Until WP05 delivers resynthesize_pipeline.py.
    """
    try:
        from .resynthesize_pipeline import run as _run  # noqa: PLC0415

        return _run(request, topic=topic, adapter=adapter)
    except ImportError as exc:
        raise NotImplementedError("resynthesize() is not yet implemented — WP05 will deliver src/charter/synthesizer/resynthesize_pipeline.py.") from exc
