"""Shared fixtures for tasks integration tests."""

from __future__ import annotations

import json
import subprocess
from datetime import UTC, datetime
from pathlib import Path

from ulid import ULID

from specify_cli.lanes.branch_naming import mid8, strip_numeric_prefix


def create_mission_fast(project: Path, slug: str, number: int = 1) -> Path:
    """Create a post-spec mission in-process, bypassing CLI subprocess overhead.

    Replicates the essential file structure downstream planning tests need
    after the specify phase: spec.md is already populated, committed, and
    substantive enough for setup-plan's entry gate. Suitable for use as
    **test setup** — not for testing the create command itself. Saves ~1 s per
    call by avoiding a full Python subprocess startup.
    """
    mission_id = str(ULID())
    human_slug = strip_numeric_prefix(slug)
    mission_slug = f"{human_slug}-{mid8(mission_id)}"
    feature_dir = project / "kitty-specs" / mission_slug

    # Directory structure
    feature_dir.mkdir(parents=True, exist_ok=True)
    (feature_dir / "checklists").mkdir(exist_ok=True)
    (feature_dir / "research").mkdir(exist_ok=True)
    tasks_dir = feature_dir / "tasks"
    tasks_dir.mkdir(exist_ok=True)

    # spec.md: setup-plan requires this to be committed and substantive.
    (feature_dir / "spec.md").write_text(
        f"""# {slug.replace("-", " ").title()}

## Functional Requirements

| ID | Requirement | Acceptance Criteria | Status |
| --- | --- | --- | --- |
| FR-001 | {slug.replace("-", " ").title()} has a planned implementation path. | The planning workflow creates and commits a valid plan. | proposed |
""",
        encoding="utf-8",
    )

    # meta.json
    meta = {
        "mission_id": mission_id,
        "mission_number": None,
        "slug": mission_slug,
        "mission_slug": mission_slug,
        "friendly_name": slug.replace("-", " "),
        "mission_type": "software-dev",
        "target_branch": "main",
        "created_at": datetime.now(UTC).isoformat(),
    }
    (feature_dir / "meta.json").write_text(
        json.dumps(meta, indent=2) + "\n",
        encoding="utf-8",
    )

    # tasks/README.md + .gitkeep
    (tasks_dir / "README.md").write_text(
        "# Work Packages\n\nGenerated by spec-kitty.\n",
        encoding="utf-8",
    )
    (tasks_dir / ".gitkeep").touch()

    # Empty event log
    (feature_dir / "status.events.jsonl").touch()

    # Single git add + commit (much faster than a CLI subprocess)
    subprocess.run(
        ["git", "add", str(feature_dir)],
        cwd=project,
        check=True,
        capture_output=True,
    )
    subprocess.run(
        ["git", "commit", "-m", f"Add spec for feature {mission_slug}"],
        cwd=project,
        check=True,
        capture_output=True,
    )

    return feature_dir
