"""Shared fixtures for tasks integration tests."""

from __future__ import annotations

import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path


def create_mission_fast(project: Path, slug: str, number: int = 1) -> Path:
    """Create a mission in-process, bypassing CLI subprocess overhead.

    Replicates the essential file structure that ``agent mission create``
    produces.  Suitable for use as **test setup** — not for testing the
    create command itself.  Saves ~1 s per call by avoiding a full Python
    subprocess startup.
    """
    mission_slug = f"{number:03d}-{slug}"
    feature_dir = project / "kitty-specs" / mission_slug

    # Directory structure
    feature_dir.mkdir(parents=True, exist_ok=True)
    (feature_dir / "checklists").mkdir(exist_ok=True)
    (feature_dir / "research").mkdir(exist_ok=True)
    tasks_dir = feature_dir / "tasks"
    tasks_dir.mkdir(exist_ok=True)

    # spec.md
    (feature_dir / "spec.md").write_text(
        f"# {slug.replace('-', ' ').title()}\n\nTODO: Add specification.\n",
        encoding="utf-8",
    )

    # meta.json
    meta = {
        "mission_number": f"{number:03d}",
        "slug": mission_slug,
        "mission_slug": mission_slug,
        "friendly_name": slug.replace("-", " "),
        "mission_type": "software-dev",
        "target_branch": "main",
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    (feature_dir / "meta.json").write_text(
        json.dumps(meta, indent=2) + "\n",
        encoding="utf-8",
    )

    # tasks/README.md + .gitkeep
    (tasks_dir / "README.md").write_text(
        "# Work Packages\n\nGenerated by spec-kitty.\n",
        encoding="utf-8",
    )
    (tasks_dir / ".gitkeep").touch()

    # Empty event log
    (feature_dir / "status.events.jsonl").touch()

    # Single git add + commit (much faster than a CLI subprocess)
    subprocess.run(
        ["git", "add", str(feature_dir)],
        cwd=project,
        check=True,
        capture_output=True,
    )
    subprocess.run(
        ["git", "commit", "-m", f"Add spec for feature {mission_slug}"],
        cwd=project,
        check=True,
        capture_output=True,
    )

    return feature_dir
