"""Agent context management commands."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional, cast

import typer
from rich.console import Console
from typing_extensions import Annotated

from specify_cli.core.paths import locate_project_root
from specify_cli.core.paths import require_explicit_feature
from specify_cli.core.execution_context import (
    ACTION_NAMES,
    ActionName,
    ActionContextError,
    resolve_action_context,
)

app = typer.Typer(
    name="context",
    help="Agent context management commands",
    no_args_is_help=True
)

console = Console()


def _find_feature_directory(repo_root: Path, cwd: Path, explicit_feature: str | None = None) -> Path:
    """Find the mission directory from an explicit mission slug.

    Args:
        repo_root: Repository root path
        cwd: Current working directory (unused — kept for signature compatibility)
        explicit_feature: Mission slug provided explicitly (required)

    Returns:
        Path to mission directory

    Raises:
        ValueError: If feature slug is not provided or directory doesn't exist
    """
    slug = require_explicit_feature(explicit_feature, command_hint="--mission <slug>")
    feature_dir = repo_root / "kitty-specs" / slug
    if not feature_dir.exists():
        raise ValueError(
            f"Mission directory not found: {feature_dir}. "
            f"Check that '{slug}' is the correct mission slug."
        )
    return feature_dir


@app.command(name="resolve")
def resolve_context(
    action: Annotated[
        str,
        typer.Option(
            "--action",
            help=(
                "Action to resolve context for "
                f"({', '.join(ACTION_NAMES)})"
            ),
        ),
    ],
    feature: Annotated[Optional[str], typer.Option("--mission", help="Mission slug (e.g., '020-my-feature')")] = None,
    wp_id: Annotated[Optional[str], typer.Option("--wp-id", help="Work package ID (e.g., WP01)")] = None,
    agent: Annotated[Optional[str], typer.Option("--agent", help="Agent name for exact command rendering")] = None,
    json_output: Annotated[bool, typer.Option("--json", help="Output results as JSON")] = False,
) -> None:
    """Resolve canonical feature/work-package/action context for prompt execution."""
    try:
        repo_root = locate_project_root()
        if repo_root is None:
            raise ActionContextError(
                "PROJECT_ROOT_UNRESOLVED",
                "Could not locate project root.",
            )

        if action not in ACTION_NAMES:
            raise ActionContextError(
                "INVALID_ACTION",
                f"Invalid action '{action}'. Expected one of: {', '.join(ACTION_NAMES)}.",
            )

        context = resolve_action_context(
            repo_root,
            action=cast(ActionName, action),
            feature=feature,
            wp_id=wp_id,
            agent=agent,
            cwd=Path.cwd(),
        )

        if json_output:
            print(json.dumps({"success": True, **context.to_dict()}, indent=2))
        else:
            console.print(f"[green]✓[/green] Resolved {action} context")
            console.print(f"  Mission: {context.mission_slug} ({context.detection_method})")
            console.print(f"  Target branch: {context.target_branch}")
            if context.wp_id:
                console.print(f"  Work package: {context.wp_id} ({context.lane})")
            if context.workspace_path:
                console.print(f"  Workspace: {context.workspace_path}")
            for name, command in context.commands.items():
                console.print(f"  {name}: {command}")
    except ActionContextError as exc:
        if json_output:
            print(json.dumps({"success": False, "error_code": exc.code, "error": str(exc)}, indent=2))
        else:
            console.print(f"[red]Error:[/red] {exc}")
        raise typer.Exit(1)



# update-context command removed — agent_context.py was deleted in WP10.
# Agent command files are now thin shims generated by shims/generator.py.
