"""Agent context management commands."""

from __future__ import annotations

import json
from pathlib import Path
from typing import cast

import typer
from rich.console import Console
from typing import Annotated

from specify_cli.cli.selector_resolution import resolve_mission_handle
from specify_cli.core.paths import locate_project_root
from specify_cli.core.execution_context import (
    ACTION_NAMES,
    ActionName,
    ActionContextError,
    resolve_action_context,
)

app = typer.Typer(name="context", help="Agent context management commands", no_args_is_help=True)

console = Console()


def _find_feature_directory(
    repo_root: Path,
    cwd: Path,
    explicit_mission: str | None = None,
    explicit_feature: str | None = None,
) -> Path:
    """Find the mission directory from an explicit mission slug.

    Uses the canonical mission resolver which handles ambiguous numeric-prefix
    handles, mid8 prefixes, and full ULID forms.

    Args:
        repo_root: Repository root path
        cwd: Current working directory (unused — kept for signature compatibility)
        explicit_mission: Mission slug provided explicitly (required)
        explicit_feature: Mission slug provided via hidden --feature alias.

    Returns:
        Path to mission directory

    Raises:
        ValueError: If mission slug is not provided or directory doesn't exist.
    """
    raw_handle = explicit_mission or explicit_feature
    if not raw_handle:
        raise ValueError("--mission <slug> is required")
    # resolve_mission_handle calls sys.exit(2) on error; on success returns ResolvedMission.
    resolved = resolve_mission_handle(raw_handle, repo_root)
    return resolved.feature_dir


@app.command(name="resolve")
def resolve_context(
    action: Annotated[
        str,
        typer.Option(
            "--action",
            help=(f"Action to resolve context for ({', '.join(ACTION_NAMES)})"),
        ),
    ],
    mission: Annotated[str | None, typer.Option("--mission", help="Mission slug (e.g., '020-my-mission')")] = None,
    feature: Annotated[str | None, typer.Option("--feature", hidden=True, help="(deprecated) Use --mission")] = None,
    wp_id: Annotated[str | None, typer.Option("--wp-id", help="Work package ID (e.g., WP01)")] = None,
    agent: Annotated[str | None, typer.Option("--agent", help="Agent name for exact command rendering")] = None,
    json_output: Annotated[bool, typer.Option("--json", help="Output results as JSON")] = False,
) -> None:
    """Resolve canonical feature/work-package/action context for prompt execution."""
    try:
        repo_root = locate_project_root()
        if repo_root is None:
            raise ActionContextError(
                "PROJECT_ROOT_UNRESOLVED",
                "Could not locate project root.",
            )

        if action not in ACTION_NAMES:
            raise ActionContextError(
                "INVALID_ACTION",
                f"Invalid action '{action}'. Expected one of: {', '.join(ACTION_NAMES)}.",
            )

        raw_handle = mission or feature
        if not raw_handle:
            raise ActionContextError("MISSING_MISSION", "--mission <slug> is required")
        mission_resolved = resolve_mission_handle(raw_handle, repo_root, json_mode=json_output)
        mission_slug = mission_resolved.mission_slug

        context = resolve_action_context(
            repo_root,
            action=cast(ActionName, action),
            feature=mission_slug,
            wp_id=wp_id,
            agent=agent,
            cwd=Path.cwd(),
        )

        if json_output:
            print(json.dumps({"success": True, **context.to_dict()}, indent=2))
        else:
            console.print(f"[green]✓[/green] Resolved {action} context")
            console.print(f"  Mission: {context.mission_slug} ({context.detection_method})")
            console.print(f"  Target branch: {context.target_branch}")
            if context.wp_id:
                console.print(f"  Work package: {context.wp_id} ({context.lane})")
            if context.workspace_path:
                console.print(f"  Workspace: {context.workspace_path}")
            for name, command in context.commands.items():
                console.print(f"  {name}: {command}")
    except ActionContextError as exc:
        if json_output:
            print(json.dumps({"success": False, "error_code": exc.code, "error": str(exc)}, indent=2))
        else:
            console.print(f"[red]Error:[/red] {exc}")
        raise typer.Exit(1) from None


# update-context command removed — agent_context.py was deleted in WP10.
# Agent command files are now thin shims generated by shims/generator.py.
