/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home */
        get: operations["home__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artifact/{feature_id}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_api_artifact__feature_id___name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/charter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Charter */
        get: operations["get_charter_api_charter_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/charter-lint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Charter Lint */
        get: operations["charter_lint_api_charter_lint_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checklists/{feature_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Checklists */
        get: operations["list_checklists_api_checklists__feature_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checklists/{feature_id}/{file_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Checklist File */
        get: operations["get_checklist_file_api_checklists__feature_id___file_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{feature_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contracts */
        get: operations["list_contracts_api_contracts__feature_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{feature_id}/{file_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contract File */
        get: operations["get_contract_file_api_contracts__feature_id___file_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Diagnostics */
        get: operations["get_diagnostics_api_diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dossier/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artifacts */
        get: operations["list_artifacts_api_dossier_artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dossier/artifacts/{artifact_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact Detail */
        get: operations["get_artifact_detail_api_dossier_artifacts__artifact_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dossier/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overview */
        get: operations["get_overview_api_dossier_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dossier/snapshots/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Snapshot */
        get: operations["export_snapshot_api_dossier_snapshots_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/missions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Mission Events
         * @description Stream mission status changes as Server-Sent Events.
         *
         *     Supports Last-Event-ID header for resumption.
         *     Returns text/event-stream media type.
         */
        get: operations["stream_mission_events_api_events_missions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/glossary-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Glossary Health */
        get: operations["glossary_health_api_glossary_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/glossary-terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Glossary Terms */
        get: operations["glossary_terms_api_glossary_terms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/missions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Missions
         * @description List all missions with HATEOAS-LITE links.
         */
        get: operations["list_missions_api_missions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/missions/{mission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Mission
         * @description Fetch a single mission by mission_id, mid8, or mission_slug.
         */
        get: operations["get_mission_api_missions__mission_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/missions/{mission_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Mission Status
         * @description Return lane counts and weighted progress for a single mission.
         */
        get: operations["get_mission_status_api_missions__mission_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/missions/{mission_id}/workpackages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Work Packages
         * @description List all work packages for a mission with HATEOAS-LITE links.
         */
        get: operations["list_work_packages_api_missions__mission_id__workpackages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/missions/{mission_id}/workpackages/{wp_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Work Package
         * @description Fetch a single work package by WP ID.
         */
        get: operations["get_work_package_api_missions__mission_id__workpackages__wp_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/{feature_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Research */
        get: operations["get_research_api_research__feature_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/{feature_id}/{file_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Research File */
        get: operations["get_research_file_api_research__feature_id___file_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Shutdown */
        post: operations["shutdown_api_shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Sync */
        post: operations["trigger_sync_api_sync_trigger_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Glossary Page */
        get: operations["glossary_page_glossary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactDirectoryFile */
        ArtifactDirectoryFile: {
            /** Icon */
            icon: string;
            /** Name */
            name: string;
            /** Path */
            path: string;
        } & {
            [key: string]: unknown;
        };
        /** ArtifactDirectoryResponse */
        ArtifactDirectoryResponse: {
            /** Files */
            files: components["schemas"]["ArtifactDirectoryFile"][];
        } & {
            [key: string]: unknown;
        };
        /** DashboardHealthInfo */
        DashboardHealthInfo: {
            /** Can Start */
            can_start?: boolean | null;
            /** Has Pid */
            has_pid?: boolean | null;
            /** Metadata Exists */
            metadata_exists?: boolean | null;
            /** Parse Error */
            parse_error?: string | null;
            /** Pid */
            pid?: number | null;
            /** Port */
            port?: number | null;
            /** Responding */
            responding?: boolean | null;
            /** Startup Error */
            startup_error?: string | null;
            /** Startup Test */
            startup_test?: string | null;
            /** Test Port */
            test_port?: number | null;
            /** Test Url */
            test_url?: string | null;
            /** Url */
            url?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * DecayWatchTileResponse
         * @description Pydantic transport model for the decay-watch tile.
         *
         *     Canonical TypedDict: :class:`dashboard.api_types.DecayWatchTileResponse`.
         *     Field names and types must stay in sync with that TypedDict.
         */
        DecayWatchTileResponse: {
            /** Contradiction Count */
            contradiction_count?: number | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Feature Scope */
            feature_scope?: string | null;
            /** Has Data */
            has_data?: boolean | null;
            /** High Severity Count */
            high_severity_count?: number | null;
            /** Orphan Count */
            orphan_count?: number | null;
            /** Reference Integrity Count */
            reference_integrity_count?: number | null;
            /** Scanned At */
            scanned_at?: string | null;
            /** Staleness Count */
            staleness_count?: number | null;
            /** Total Count */
            total_count?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** DiagnosticsFeatureStatus */
        DiagnosticsFeatureStatus: {
            /** Artifacts In Main */
            artifacts_in_main: boolean | string[];
            /** Artifacts In Worktree */
            artifacts_in_worktree: boolean | string[];
            /** Branch Exists */
            branch_exists: boolean;
            /** Branch Merged */
            branch_merged: boolean;
            /** Name */
            name: string;
            /** State */
            state: string;
            /** Worktree Exists */
            worktree_exists: boolean;
            /** Worktree Path */
            worktree_path?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** DiagnosticsResponse */
        DiagnosticsResponse: {
            /** Active Mission */
            active_mission?: string | null;
            /** All Features */
            all_features: components["schemas"]["DiagnosticsFeatureStatus"][];
            /** Current Feature */
            current_feature: {
                [key: string]: unknown;
            };
            /** Current Working Directory */
            current_working_directory: string;
            dashboard_health: components["schemas"]["DashboardHealthInfo"];
            file_integrity: components["schemas"]["FileIntegrity"];
            /** Git Branch */
            git_branch?: string | null;
            /** In Worktree */
            in_worktree: boolean;
            /** Issues */
            issues: string[];
            /** Observations */
            observations: string[];
            /** Project Path */
            project_path: string;
            /** Worktree Overview */
            worktree_overview: {
                [key: string]: unknown;
            };
            /** Worktrees Exist */
            worktrees_exist: boolean;
        } & {
            [key: string]: unknown;
        };
        /** FileIntegrity */
        FileIntegrity: {
            /** Missing Files */
            missing_files: string[];
            /** Total Expected */
            total_expected: number;
            /** Total Missing */
            total_missing: number;
            /** Total Present */
            total_present: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * GlossaryHealthResponse
         * @description Pydantic transport model for the glossary health endpoint.
         *
         *     Canonical TypedDict: :class:`specify_cli.glossary.types.GlossaryHealthResponse`.
         *     Field names and types must stay in sync with that TypedDict.
         */
        GlossaryHealthResponse: {
            /** Active Count */
            active_count?: number | null;
            /** Deprecated Count */
            deprecated_count?: number | null;
            /** Draft Count */
            draft_count?: number | null;
            /** Entity Pages Generated */
            entity_pages_generated?: boolean | null;
            /** Entity Pages Path */
            entity_pages_path?: string | null;
            /** High Severity Drift Count */
            high_severity_drift_count?: number | null;
            /** Last Conflict At */
            last_conflict_at?: string | null;
            /** Orphaned Term Count */
            orphaned_term_count?: number | null;
            /** Total Terms */
            total_terms?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * GlossaryTermRecord
         * @description Pydantic transport model for a single glossary term.
         *
         *     Canonical TypedDict: :class:`specify_cli.glossary.types.GlossaryTermRecord`.
         *     Field names and types must stay in sync with that TypedDict.
         */
        GlossaryTermRecord: {
            /** Confidence */
            confidence: number;
            /** Definition */
            definition: string;
            /** Status */
            status: string;
            /** Surface */
            surface: string;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Project Path */
            project_path?: string | null;
            /** Status */
            status?: string | null;
            sync?: components["schemas"]["SyncInfo"] | null;
            /** Token */
            token?: string | null;
            /** Websocket Status */
            websocket_status?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * LaneCounts
         * @description Lane-keyed integer counts for a mission's work packages.
         */
        LaneCounts: {
            /**
             * Approved
             * @default 0
             */
            approved: number;
            /**
             * Blocked
             * @default 0
             */
            blocked: number;
            /**
             * Canceled
             * @default 0
             */
            canceled: number;
            /**
             * Claimed
             * @default 0
             */
            claimed: number;
            /**
             * Done
             * @default 0
             */
            done: number;
            /**
             * For Review
             * @default 0
             */
            for_review: number;
            /**
             * In Progress
             * @default 0
             */
            in_progress: number;
            /**
             * In Review
             * @default 0
             */
            in_review: number;
            /**
             * Planned
             * @default 0
             */
            planned: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * Link
         * @description A single HATEOAS-LITE hyperlink. Subset of HAL's link object.
         *
         *     See doctrine paradigm ``hateoas-lite`` (src/doctrine/paradigms/shipped/
         *     hateoas-lite.paradigm.yaml) for the full convention and future-graduation
         *     triggers (HAL / JSON:API).
         */
        Link: {
            /** Href */
            href: string;
            /**
             * Method
             * @default GET
             */
            method: string;
        };
        /**
         * Mission
         * @description Full mission detail representation.
         */
        Mission: {
            /** Links */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /** Created At */
            created_at?: string | null;
            /** Friendly Name */
            friendly_name: string;
            /**
             * Is Legacy
             * @default false
             */
            is_legacy: boolean;
            lane_counts: components["schemas"]["LaneCounts"];
            /** Mid8 */
            mid8: string;
            /** Mission Id */
            mission_id: string;
            /** Mission Number */
            mission_number?: number | null;
            /** Mission Slug */
            mission_slug: string;
            /** Mission Type */
            mission_type: string;
            /** Target Branch */
            target_branch: string;
            /** Weighted Percentage */
            weighted_percentage?: number | null;
        };
        /**
         * MissionStatus
         * @description Lane counts and progress for a single mission — polling-friendly.
         */
        MissionStatus: {
            /** Links */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /**
             * Current Phase
             * @default 2
             */
            current_phase: number;
            /** Done Count */
            done_count: number;
            lane_counts: components["schemas"]["LaneCounts"];
            /** Mission Id */
            mission_id: string;
            /** Total Count */
            total_count: number;
            /** Weighted Percentage */
            weighted_percentage?: number | null;
        };
        /**
         * MissionSummary
         * @description Lightweight mission representation for list responses.
         */
        MissionSummary: {
            /** Links */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            /** Friendly Name */
            friendly_name: string;
            /**
             * Is Legacy
             * @default false
             */
            is_legacy: boolean;
            lane_counts: components["schemas"]["LaneCounts"];
            /** Mid8 */
            mid8: string;
            /** Mission Id */
            mission_id: string;
            /** Mission Number */
            mission_number?: number | null;
            /** Mission Slug */
            mission_slug: string;
            /** Mission Type */
            mission_type: string;
            /** Target Branch */
            target_branch: string;
            /** Weighted Percentage */
            weighted_percentage?: number | null;
        };
        /** ResearchArtifact */
        ResearchArtifact: {
            /** Icon */
            icon: string;
            /** Name */
            name: string;
            /** Path */
            path: string;
        } & {
            [key: string]: unknown;
        };
        /** ResearchResponse */
        ResearchResponse: {
            /** Artifacts */
            artifacts: components["schemas"]["ResearchArtifact"][];
            /** Main File */
            main_file?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ReviewEvidence
         * @description Evidence from a review event (in_review -> approved/rejected).
         */
        ReviewEvidence: {
            /** Notes */
            notes?: string | null;
            /**
             * Reviewed At
             * Format: date-time
             */
            reviewed_at: string;
            /** Reviewed By */
            reviewed_by: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "approved" | "rejected";
        };
        /** ShutdownResponse */
        ShutdownResponse: {
            /**
             * Status
             * @constant
             */
            status: "stopping";
        } & {
            [key: string]: unknown;
        };
        /**
         * SyncInfo
         * @description Nested sync block; all keys optional matching `total=False`.
         */
        SyncInfo: {
            /** Consecutive Failures */
            consecutive_failures?: number | null;
            /** Error */
            error?: string | null;
            /** Last Sync */
            last_sync?: string | null;
            /** Running */
            running?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /** SyncTriggerFailedResponse */
        SyncTriggerFailedResponse: {
            /** Error */
            error: string;
        } & {
            [key: string]: unknown;
        };
        /** SyncTriggerScheduledResponse */
        SyncTriggerScheduledResponse: {
            /**
             * Status
             * @constant
             */
            status: "scheduled";
        } & {
            [key: string]: unknown;
        };
        /** SyncTriggerSkippedResponse */
        SyncTriggerSkippedResponse: {
            /** Manual Mode */
            manual_mode: boolean;
            /** Reason */
            reason?: string | null;
            /**
             * Status
             * @constant
             */
            status: "skipped";
        } & {
            [key: string]: unknown;
        };
        /** SyncTriggerUnavailableResponse */
        SyncTriggerUnavailableResponse: {
            /** Error */
            error: string;
            /** Reason */
            reason?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkPackage
         * @description Full WP detail representation.
         */
        WorkPackage: {
            /** Links */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            assignment: components["schemas"]["WorkPackageAssignment"];
            /** Dependencies */
            dependencies: string[];
            /** Prompt Ref */
            prompt_ref?: string | null;
            /** Requirement Refs */
            requirement_refs: string[];
            /** Subtasks Done */
            subtasks_done: number;
            /** Subtasks Total */
            subtasks_total: number;
            /** Title */
            title: string;
            /** Wp Id */
            wp_id: string;
        };
        /**
         * WorkPackageAssignment
         * @description Ownership contract for a single WP.
         */
        WorkPackageAssignment: {
            /** Agent Profile */
            agent_profile?: string | null;
            /** Assignee */
            assignee?: string | null;
            /** Blocked Reason */
            blocked_reason?: string | null;
            /** Claimed At */
            claimed_at?: string | null;
            /** Lane */
            lane: string;
            /** Last Event Id */
            last_event_id?: string | null;
            review_evidence?: components["schemas"]["ReviewEvidence"] | null;
            /** Role */
            role?: string | null;
            /** Wp Id */
            wp_id: string;
        };
        /**
         * WorkPackageSummary
         * @description Lightweight WP representation for list responses.
         */
        WorkPackageSummary: {
            /** Links */
            _links?: {
                [key: string]: components["schemas"]["Link"];
            };
            assignment: components["schemas"]["WorkPackageAssignment"];
            /** Title */
            title: string;
            /** Wp Id */
            wp_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    home__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    get_artifact_api_artifact__feature_id___name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_charter_api_charter_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    charter_lint_api_charter_lint_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecayWatchTileResponse"];
                };
            };
        };
    };
    list_checklists_api_checklists__feature_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactDirectoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_checklist_file_api_checklists__feature_id___file_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: string;
                file_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_contracts_api_contracts__feature_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactDirectoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contract_file_api_contracts__feature_id___file_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: string;
                file_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_diagnostics_api_diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticsResponse"];
                };
            };
        };
    };
    list_artifacts_api_dossier_artifacts_get: {
        parameters: {
            query?: {
                feature?: string | null;
                class?: string | null;
                wp_id?: string | null;
                step_id?: string | null;
                required_only?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_detail_api_dossier_artifacts__artifact_key__get: {
        parameters: {
            query?: {
                feature?: string | null;
            };
            header?: never;
            path: {
                artifact_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overview_api_dossier_overview_get: {
        parameters: {
            query?: {
                feature?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_snapshot_api_dossier_snapshots_export_get: {
        parameters: {
            query?: {
                feature?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_mission_events_api_events_missions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    glossary_health_api_glossary_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryHealthResponse"];
                };
            };
        };
    };
    glossary_terms_api_glossary_terms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryTermRecord"][];
                };
            };
        };
    };
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_missions_api_missions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionSummary"][];
                };
            };
        };
    };
    get_mission_api_missions__mission_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mission"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mission_status_api_missions__mission_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_work_packages_api_missions__mission_id__workpackages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkPackageSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_work_package_api_missions__mission_id__workpackages__wp_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
                wp_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkPackage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_research_api_research__feature_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_research_file_api_research__feature_id___file_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: string;
                file_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shutdown_api_shutdown_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShutdownResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_sync_api_sync_trigger_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncTriggerScheduledResponse"] | components["schemas"]["SyncTriggerSkippedResponse"] | components["schemas"]["SyncTriggerUnavailableResponse"] | components["schemas"]["SyncTriggerFailedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    glossary_page_glossary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
}
