"""Reappearance guard: no ``*parity_scaffold*`` artifact survives (C-004).

WP05 retires the transitional software-dev
byte-parity scaffold that shadowed ``resolve_mission_type_context`` while the
template authority swap was verified. Scaffolding of that shape is
explicitly transitional per FR-008/C-004 — useful during the swap, but a
liability if left behind: it doubles maintenance on an already-superseded
code path and invites drift between the "real" resolver and its scaffold
double.

This gate is a permanent reappearance guard, not a one-shot cleanup check: it
fails the build the moment any future change (re-)introduces a
``*parity_scaffold*``-named file anywhere under ``src/`` or ``tests/``,
whatever the underlying seam. See
``tests/charter/test_resolved_mission_type_context.py`` for the enduring
determinism assertions the scaffold was standing in for.
"""

from __future__ import annotations

import ast
from pathlib import Path

import pytest

pytestmark = pytest.mark.architectural

_REPO_ROOT = Path(__file__).resolve().parents[2]
_SCAN_ROOTS: tuple[Path, ...] = (_REPO_ROOT / "src", _REPO_ROOT / "tests")
_PATTERN = "*parity_scaffold*"
#: This guard's own filename intentionally contains "parity_scaffold" (it is
#: the "no parity scaffold" guard, not a scaffold itself). Only this exact
#: source and its own generated bytecode are exempt; other ``__pycache__``
#: artifacts remain migration residue and must fail the gate.
_SELF_PATH = Path(__file__).resolve()
_SPEC_READER = _REPO_ROOT / "src/specify_cli/core/mission_creation.py"
_PLAN_READER = _REPO_ROOT / "src/specify_cli/cli/commands/agent/mission_setup_plan.py"


def _is_guard_self_artifact(path: Path, self_path: Path) -> bool:
    resolved = path.resolve()
    resolved_self = self_path.resolve()
    if resolved == resolved_self:
        return True
    return (
        resolved.suffix == ".pyc"
        and resolved.parent.name == "__pycache__"
        and resolved.parent.parent == resolved_self.parent
        and resolved.name.startswith(f"{resolved_self.stem}.")
    )


def _parity_scaffold_paths(
    scan_roots: tuple[Path, ...] = _SCAN_ROOTS,
    self_path: Path = _SELF_PATH,
) -> list[Path]:
    hits: list[Path] = []
    for root in scan_roots:
        if not root.is_dir():
            continue
        for path in sorted(root.rglob(_PATTERN)):
            if _is_guard_self_artifact(path, self_path):
                continue
            hits.append(path)
    return hits


def test_no_parity_scaffold_artifact_survives() -> None:
    offenders = _parity_scaffold_paths()
    assert not offenders, (
        "A transitional '*parity_scaffold*' artifact survived past its WP "
        "(FR-008/C-004 — scaffolding must be deleted before landing, not left as "
        "permanent duplicate coverage):\n" + "\n".join(str(path.relative_to(_REPO_ROOT)) for path in offenders)
    )


def test_scaffold_bytecode_is_not_hidden_by_self_artifact_exception(
    tmp_path: Path,
) -> None:
    tests_root = tmp_path / "tests"
    guard = tests_root / "architectural" / "test_no_parity_scaffold.py"
    guard.parent.mkdir(parents=True)
    guard.write_text("# permanent guard\n", encoding="utf-8")
    own_bytecode = guard.parent / "__pycache__" / "test_no_parity_scaffold.cpython-312.pyc"
    own_bytecode.parent.mkdir()
    own_bytecode.write_bytes(b"permanent guard bytecode")
    stale_bytecode = tests_root / "integration" / "__pycache__" / "test_template_resolution_parity_scaffold.cpython-312.pyc"
    stale_bytecode.parent.mkdir(parents=True)
    stale_bytecode.write_bytes(b"stale transitional bytecode")

    assert _parity_scaffold_paths((tests_root,), guard) == [stale_bytecode]


def _function(path: Path, name: str) -> ast.FunctionDef:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    matches = [node for node in tree.body if isinstance(node, ast.FunctionDef) and node.name == name]
    assert len(matches) == 1, f"Expected exactly one {name}() in {path}"
    return matches[0]


def _qualified_name(node: ast.expr) -> tuple[str, ...]:
    if isinstance(node, ast.Name):
        return (node.id,)
    if isinstance(node, ast.Attribute):
        owner = _qualified_name(node.value)
        return (*owner, node.attr) if owner else ()
    return ()


def _calls(function: ast.FunctionDef, qualified_name: tuple[str, ...]) -> list[ast.Call]:
    return [node for node in ast.walk(function) if isinstance(node, ast.Call) and _qualified_name(node.func) == qualified_name]


def _first_string_argument(call: ast.Call) -> str | None:
    if not call.args:
        return None
    first = call.args[0]
    return first.value if isinstance(first, ast.Constant) and isinstance(first.value, str) else None


def _is_exact_typeless_legacy_guard(node: ast.If, legacy_call: ast.Call) -> bool:
    match node.test:
        case ast.Compare(
            left=ast.Attribute(
                value=ast.Name(id="resolved_mission_type"),
                attr="mission_type",
            ),
            ops=[ast.Is()],
            comparators=[ast.Constant(value=None)],
        ):
            return not node.orelse and any(isinstance(statement, ast.Return) and statement.value is legacy_call for statement in node.body)
        case _:
            return False


def test_production_readers_use_configured_mapping_seam() -> None:
    """Reader call sites select semantic keys, not magic template filenames."""
    spec_reader = _function(_SPEC_READER, "create_mission_core")
    plan_reader = _function(_PLAN_READER, "_resolve_plan_template")

    spec_calls = _calls(spec_reader, ("resolve_configured_template",))
    plan_calls = _calls(plan_reader, ("_mission", "resolve_configured_template"))
    assert [_first_string_argument(call) for call in spec_calls] == ["spec"]
    assert [_first_string_argument(call) for call in plan_calls] == ["plan"]

    assert not _calls(spec_reader, ("resolve_template",))
    spec_literals = {node.value for node in ast.walk(spec_reader) if isinstance(node, ast.Constant) and isinstance(node.value, str)}
    assert "spec-template.md" not in spec_literals
    assert "software-dev-default" not in spec_literals


def test_plan_legacy_selector_is_confined_to_typeless_compatibility_branch() -> None:
    """The temporary #2660 boundary cannot become the activated reader path."""
    plan_reader = _function(_PLAN_READER, "_resolve_plan_template")
    legacy_calls = _calls(plan_reader, ("_mission", "resolve_template"))
    assert len(legacy_calls) == 1
    legacy_call = legacy_calls[0]
    assert _first_string_argument(legacy_call) == "plan-template.md"

    typeless_guard = next(
        (node for node in ast.walk(plan_reader) if isinstance(node, ast.If) and _is_exact_typeless_legacy_guard(node, legacy_call)),
        None,
    )
    assert typeless_guard is not None, "Legacy plan selection escaped its exact `mission_type is None` body"
    configured_calls = _calls(plan_reader, ("_mission", "resolve_configured_template"))
    assert [_first_string_argument(call) for call in configured_calls] == ["plan"]

    plan_literals = {node.value for node in ast.walk(plan_reader) if isinstance(node, ast.Constant) and isinstance(node.value, str)}
    assert "software-dev-default" not in plan_literals


@pytest.mark.parametrize(
    ("operator", "expected"),
    [("is", True), ("is not", False)],
)
def test_typeless_guard_helper_rejects_inverse_mutation(
    operator: str,
    expected: bool,
) -> None:
    function = ast.parse(
        "def reader(resolved_mission_type):\n"
        f"    if resolved_mission_type.mission_type {operator} None:\n"
        "        return resolve_template('plan-template.md')\n"
        "    return resolve_configured_template('plan')\n"
    ).body[0]
    assert isinstance(function, ast.FunctionDef)
    guard = function.body[0]
    assert isinstance(guard, ast.If)
    legacy_call = _calls(function, ("resolve_template",))[0]

    assert _is_exact_typeless_legacy_guard(guard, legacy_call) is expected


@pytest.mark.parametrize(
    "receiver",
    ["context", "other", "resolved_mission_type.context"],
)
def test_typeless_guard_helper_rejects_wrong_receiver(receiver: str) -> None:
    function = ast.parse(
        "def reader(resolved_mission_type):\n"
        f"    if {receiver}.mission_type is None:\n"
        "        return resolve_template('plan-template.md')\n"
        "    return resolve_configured_template('plan')\n"
    ).body[0]
    assert isinstance(function, ast.FunctionDef)
    guard = function.body[0]
    assert isinstance(guard, ast.If)
    legacy_call = _calls(function, ("resolve_template",))[0]

    assert not _is_exact_typeless_legacy_guard(guard, legacy_call)
