"""Hidden CLI entrypoint for the pre-commit hook's install-agnostic fallback.

``spec-kitty commit-guard-hook`` is the run-time fallback the pre-commit hook
generated by ``policy/hook_installer.py`` execs when its pinned interpreter no
longer exists (issue #254 — a pipx -> uv, or any other, install-method
migration moves the interpreter). Unlike the pinned path, this is resolved
fresh off ``PATH`` at hook run time, so it keeps working across an install
migration as long as *some* current, working ``spec-kitty`` install put a
console script on ``PATH`` — which is definitionally true right after any
successful install or upgrade.

Never invoked directly by a person; git invokes it (via the hook's shell
fallback branch) with zero arguments, exactly like the primary
``-m specify_cli.policy.commit_guard_hook`` path it mirrors.
"""

from __future__ import annotations

from typing import Annotated

import typer


def commit_guard_hook_cli(
    _args: Annotated[
        list[str] | None,
        typer.Argument(hidden=True, help="Ignored; accepted for parity with the primary hook path."),
    ] = None,
) -> None:
    """Run the commit guard and exit with its result code."""
    from specify_cli.policy.commit_guard_hook import main

    raise typer.Exit(code=main())
